a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um nùmero?', a. isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Esta em maisculas?', a.isupper())
print('Esta em minusculas?', a.islower())
print('Está capitalizada?', a.istitle())
